apiVersion: apps/v1
kind: Deployment
metadata:
  name: prilor-hrms
spec:
  replicas: 2
  selector:
    matchLabels:
      app: prilor-hrms
  template:
    metadata:
      labels:
        app: prilor-hrms
    spec:
      containers:
      - name: prilor-hrms
        image: rkumarbengaluru/prilor-hrms
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: prilor-hrms
spec:
  selector:
    app: prilor-hrms
  ports:
  - port: 8080
    targetPort: 8080
  type: LoadBalancer
