kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: nginx-deployment
spec:
  replicas: 4
  strategy: Recreate
  selector:
    matchLabels:
      deploy: example
  template:
    spec:
      containers:
      - name: nginx
        image: nginx:1.7.9
