apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 4
  strategy: Recreate
  selector:
    matchLabels:
      app: nginx-deployment
  template:
    metadata:
        labels:
          app: nginx-deployment
  spec:
      containers:
      - name: nginx
        image: nginx
