apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: k8s-node-to-nginx
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: k8s-node-to-nginx
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50